name: 'Create ec2 multi az'

on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read 
env: 
  AWS_REGION: ap-south-1
  TF_VERSION: 1.2.6   

jobs:
  terraform:
    name: infrastructure-staging
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}      

    - name: Terraform Init
      run: |
        cd terraform
        cd ec2-load-balancer-multi-az
        terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate -no-color      

    - name: Terraform Plan
      run: terraform plan --var-file=staging.terraform.tfvars  

    - name: Terraform Apply
      run: terraform apply --auto-approve --var-file=staging.terraform.tfvars  
      
